# Generated by Django 3.1.5 on 2021-01-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontside', models.CharField(max_length=24)),
                ('backside', models.CharField(max_length=24)),
                ('answer', models.CharField(max_length=44)),
            ],
        ),
    ]
